- hosts: all
  become: true
  tasks: 
    # Add pve-no-subscription repository into sources list.
    apt_repository:
      repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
      state: present

    # Add ceph-quincy bookworm no-subscription repository into sources list.
    apt_repository:
      repo: http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
      state: present
      
    apt_key:
      url: 'https://pkgs.tailscale.com/stable/ubuntu/focal.gpg'
      
    apt_repository:
      repo: https://pkgs.tailscale.com/stable/debian bookworm main
      state: present
      
    apt_repository:
      repo: https://repo.zabbix.com/zabbix/6.4/debian bookworm main
      state: present
    
