---
- hosts: all
  become: true
  tasks:
    - name: update apt
	# Add pve-no-subscription repository into sources list.
 	apt_repository:
      	repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
	state: present
