---
 - name: Playbook to install stuffs
   hosts: all
   become: true
   tasks: 
    - name: Add specified repository into sources list
        ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        state: present
