---
- hosts: all
  tasks:
  - name: Add Tailscale GPG key
    apt_key:
      url: 'https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg'

  - name: Add PVE no-subscription APT repository
    apt_repository:
      repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

  - name: Add Ceph no-subscription APT repository
    apt_repository:
      repo: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription

  - name: Add Tailscale no-subscription APT repository
    apt_repository:
      repo: deb https://pkgs.tailscale.com/stable/debian bookworm main

  - name: Add Zabbix 6.4 APT repository
    apt_repository:
      repo: deb https://repo.zabbix.com/zabbix/6.4/debian bookworm main
