---
- hosts: all
  become: true
  tasks:
    - name: update apt
	ansible.builtin.apt_repository:
      	 repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
	 state: present
